spring:
  application:
    name: book-api
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/challenge}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  data:
    web:
      pageable:
        one-indexed-parameters: true
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: ${JPA_SHOW_SQL:false}
server:
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 1024
